name: rfaye3
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: null
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: null
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_facebook_auth: ^7.1.1
  flutter_lazy_indexed_stack: ^0.0.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  modal_progress_hud_nsn: ^0.5.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3
  supabase_flutter: null
  svg_flutter: ^0.0.1
  top_snackbar_flutter: ^3.2.0

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  intl_utils: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/vuesax/bold/
    - assets/images/vuesax/outline/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: null
